<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheelybot">

  <xacro:property name="big_radius" value="0.1" />
  <xacro:property name="small_radius" value="0.1" />
  <xacro:property name="wheel_thickness" value="0.04" />
  <xacro:property name="chassis_length" value="0.5" />
  <xacro:property name="chassis_width" value="0.5" />
  <xacro:property name="chassis_height" value="0.3" />

  <xacro:property name="chassis_mass" value="5.0" />
  <xacro:property name="wheel_mass" value="0.5" />
  <xacro:property name="caster_mass" value="0.5" />

  <!-- Rviz colors -->
  <xacro:include filename="$(find wheelybot_description)/urdf/materials.xacro"/>

  <!-- Base  -->
  <link name="base_link"></link>

  <joint name="base_to_chassis" type="fixed">
    <origin xyz="0 0 ${big_radius+chassis_height/2}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="chassis"/>
  </joint>

  <!-- Chassis -->
  <link name="chassis">

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia
          ixx="${chassis_mass / 12.0 * (chassis_width*chassis_width + chassis_height*chassis_height)}" ixy="0.0" ixz="0.0"
          iyy="${chassis_mass / 12.0 * (chassis_height*chassis_height + chassis_width*chassis_width)}" iyz="0.0"
          izz="${chassis_mass / 12.0 * (chassis_width*chassis_width + chassis_width*chassis_width)}"/>
    </inertial>

  </link>

  <!-- Left Wheel -->
  <link name="left_wheel">

    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${big_radius}"/>
      </geometry>
      <material name="light_grey"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${big_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}"/>
      <inertia
          ixx="${wheel_mass / 12.0 * wheel_thickness*wheel_thickness}" ixy="0.0" ixz="0.0"
          iyy="0" iyz="0.0"
          izz="${wheel_mass / 12.0 * wheel_thickness*wheel_thickness}"/>
    </inertial>

  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="${-chassis_length/3} ${chassis_width/2+wheel_thickness/2+0.001} ${big_radius}" rpy="${-pi/2} 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <!-- Right Wheel -->
  <link name="right_wheel">

    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${big_radius}"/>
      </geometry>
      <material name="light_grey"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${big_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${wheel_mass}"/>
      <inertia
          ixx="${wheel_mass / 12.0 * wheel_thickness*wheel_thickness}" ixy="0.0" ixz="0.0"
          iyy="0" iyz="0.0"
          izz="${wheel_mass / 12.0 * wheel_thickness*wheel_thickness}"/>
    </inertial>

  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="${-chassis_length/3} ${-chassis_width/2-wheel_thickness/2-0.001} ${big_radius}" rpy="${pi/2} 0 0"/>
    <axis xyz="0 0 -1"/>
  </joint>

  <!-- Caster ball -->
  <link name="caster_ball">

    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <sphere radius="${small_radius}"/>
      </geometry>
      <material name="dark_grey"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${small_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${caster_mass}"/>
      <inertia
          ixx="${2/5.0 * caster_mass * small_radius*small_radius}" ixy="0.0" ixz="0.0"
          iyy="${2/5.0 * caster_mass * small_radius*small_radius}" iyz="0.0"
          izz="${2/5.0 * caster_mass * small_radius*small_radius}"/>
    </inertial>

  </link>

  <joint name="caster_ball_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_ball"/>
    <origin xyz="${chassis_length/2} 0 ${small_radius}" rpy="${pi/2} 0 0"/>
  </joint>

  <!-- Sensor descriptions -->
  <xacro:include filename="$(find wheelybot_description)/urdf/lidar.xacro"/>

</robot>
