controller_manager:
  ros__parameters:
    update_rate: 30

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:

    publish_rate: 30.0
    odom_frame_id: odom
    base_frame_id: base_link

    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']

    # Should match wheelybot_description urdf
    wheel_separation: 0.54
    wheel_radius: 0.1

    use_stamped_vel: false
